minor fixes

diff --git a/image-download b/image-download
--- a/image-download
+++ b/image-download
@@ -10,6 +10,11 @@ path="$folder/$repo/$tag"
 
 registry_uri=https://registry-1.docker.io/v2
 
+function die(){
+    echo "Error: $1" 1>&2
+    exit 1
+}
+
 function help(){
     echo "Usage: $(basename $0) <repo>/<image>:<tag>"
     exit 0
@@ -17,13 +22,11 @@ function help(){
 [[ $1 =~ ^[a-z0-9_-]+/[a-z0-9_-]+:[a-z0-9_-]+$ ]] || help
 
 if ! command -v jq &> /dev/null; then
-    echo "jq is not installed. Exiting."
-    exit 1
+    die "jq is not installed!"
 fi
 
 if [ -d "$path" ];then
-    echo "Image already downloaded in $path"
-    exit 1
+    die "Image already downloaded in $path"
 fi
 
 function get_token(){
@@ -38,7 +41,13 @@ function get_manifest(){
     local apii="application/vnd.oci.image.manifest.v1+json"
     local url="$registry_uri/$1/manifests/$2"
     
-    curl -H "Accept: ${apil}" -H "Accept: ${api}" -H "Accept: ${apii}" -H "Authorization: Bearer $3" -s "$url"
+    local resp=$(curl -H "Accept: ${apil}" -H "Accept: ${api}" -H "Accept: ${apii}" -H "Authorization: Bearer $3" -s "$url")
+
+    if echo $resp | jq -e '.errors' > /dev/null; then
+        die "Image $repo:$tag doesn't exist!"
+    fi
+
+    echo "$resp"
 }
 
 function get_layer(){
diff --git a/image-upload b/image-upload
--- a/image-upload
+++ b/image-upload
@@ -12,6 +12,11 @@ path="$folder/$repo/$tag"
 
 registry_uri=https://registry-1.docker.io/v2
 
+function die(){
+    echo "Error: $1" 1>&2
+    exit 1
+}
+
 function help(){
     echo "Usage: $(basename $0) <repo>/<image>:<tag>"
     exit 0
@@ -20,8 +25,7 @@ function help(){
 [[ $1 =~ ^[a-z0-9_-]+/[a-z0-9_-]+:[a-z0-9_-]+$ ]] || help
 
 if ! command -v jq &> /dev/null; then
-    echo "jq is not installed. Exiting."
-    exit 1
+    die "jq is not installed!"
 fi
 
 function get_token(){
@@ -74,14 +78,14 @@ function put_image(){
 }
 
 if [ ! -d "$path" ];then
-    echo "No filesystem found in: $path"
-    exit 1
+    die "No filesystem found in: $path"
 fi
 
 if [ -x "$DOCKER_USERNAME" -o -x "$DOCKER_PASSWORD" ];then
     echo "Following environment variables need to be exported:"
     echo -e "\texport DOCKER_USERNAME=<ducker-hub-username>"
     echo -e "\texport DOCKER_PASSWORD=<ducker-hub-password>"
+    die "No user or password provided!"
 fi
 
 # Only create config.yaml if not exist
